### ISSUE TITLE
Command line switches fail silently from os2 command shells

### ISSUE THREAD

**Issue by Greggk** [bitwiseworks/otter-browser-os2#6] opened 2022-01-23 18:08 UTC
I have tried running otter-browser.exe from a 4OS2 command line with the -v --version -h --help and --new-tab URL. They all fail silently. I tried it with -h from cmd which also fails silently. otter-browser.exe URL opens the URL in a new browser window.  Using Dash works to show the help.

**Comment by dmik** [comment] 2022-01-24 18:03
It's actually not a bug. The Otter executable is marked as WINDOWED (PM), not VIO. It means that CMD.EXE (and I suppose 4OS2 too) will start it in a separate session w/o console attached. Hence the standard output just goes nowhere (to NUL). If you redirect the output to a file manually, e.g.
```sh
otter-browser.exe -h >output.txt
```
you will get what you need.

Dash works differently, it still attaches the console even to WINDOWED applications so it gets their output.

If you e.g. want to have Otter show a nice GUI window instead of sending -h -v and similar results to the standard output, please file a enhancement ticked. Closing this one.

**Closed as completed by dmik** 2022-01-24 18:03 UTC
